### ISSUE TITLE
Error: Unable to load config file 'kubernix-run/kubernix.toml'

### ISSUE THREAD

**Issue by amackillop** [saschagrunert/kubernix#26]
This was working up until today but after building and running `sudo kubernix` I get this error:
`Error: Unable to load config file 'kubernix-run/kubernix.toml':  missing field `impure` at line 1 column 1`

It looks like something simple and I will look into it. Running this on Manjaro.

This si what the kubernix-run/kubernix.toml file looks like:
```
root = "kubernix-run"
log-level = "INFO"
crio-cidr = "10.100.0.0/16"
cluster-cidr = "10.200.0.0/16"
service-cidr = "10.50.0.0/24"
```

**Comment by saschagrunert** [comment]
Hey, yeah sorry the configurations are incompatible, you can either remove it or add the missing fields manually.

**Comment by saschagrunert** [comment]
So the current working configuration would look like: 

```toml
root = "kubernix-run"
log-level = "DEBUG"
crio-cidr = "10.100.0.0/16"
cluster-cidr = "10.200.0.0/16"
service-cidr = "10.50.0.0/16"
impure = false
packages = []
```
